### ISSUE TITLE
M335 Template needs extra R chunk

### ISSUE THREAD

**Issue by hathawayj** [dylanjm/Rtemplates#7]
Dylan,

   When we took the message and warning out of the YAML it messed up the options chunk.  You need a chunk that just has the options set where echo=FALSE.  The second chunk would be the libraries chunk.

J.

**Comment by dylanjm** [comment]
@hathawayj Do you think it would be better to have all the chunk related options set in the first chunk? Meaning we take things like fig.width, fig.align, etc. out of the YAML and put it in the options chunk setting function. Here's what I mean:

__Current Options Chunk__
``` r
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

__My Suggestion__
``` r
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.height=6, fig.width=12,fig.align='center',collapse=TRUE)
```
